const MISSILE_ROUTE_COMMAND = {
  PLAYER_STRAIGHT: "PLAYER_STRAIGHT",
  ENEMY_STRAIGHT: "ENEMY_STRAIGHT",
  ENEMY_AIMED: "ENEMY_AIMED",
  ENEMY_ALLWAY: "ENEMY_ALLWAY",
  GUIDED: "GUIDED",
};

export default MISSILE_ROUTE_COMMAND;
