const MISSILE_ROUTE_COMMAND = {
  PLATER_STRAIGHT: "PLATER_STRAIGHT",
  ENEMY_STRAIGHT: "ENEMY_STRAIGHT",
  ENEMY_AIMED: "ENEMY_AIMED",
  ENEMY_GUIDED: "ENEMY_GUIDED",
  ENEMY_ALLWAY: "ENEMY_ALLWAY",
};

export default MISSILE_ROUTE_COMMAND;
